GET https://graphhopper.com/maps/?point=41.341668%2C69.336452_Current+Location&point=41.341668%2C69.336452_Current+Location&point=48.8177%2C5.892_Minorville%2C+54385%2C+Grand+Est%2C+France&profile=car&layer=Omniscale
