spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fastfood
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 9090
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

  minio:
      application: fastFood
      host: https://localhost:9090
      username: fastFood
      password: fastFood


springdoc:
  swagger-ui:
    path: /